version: '3.7'

services:
  application:
    image: app/server:latest
    volumes:
      - ./app:/var/www
    ports:
      - 80:80
  database:
    image: postgres:12
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
